### ISSUE TITLE
Log in credential

### ISSUE THREAD

**Issue by wangw-moodys** [LTD-Beget/sprutio#100]
Hi, I followed the instruction to download the sprutio on my linux server, however, what it the log in credential for initial login and password?

**Comment by jerrdasur** [comment]
Hi, @AndrewProcess 

README says: `To log in, please use any of your system's credentials`. Sprutio uses your server's user credentials from `/etc/passwd`.

Sorry for possible mistakes in my English.

**Comment by wangw-moodys** [comment]
Hi, 
Thanks for the answer, however, the way I log in my server is using ssa key, is there any other way I can log in? 

Thanks
