### ISSUE TITLE
Cient version 1.18 is too old. Minimum supported API version is 1.24, please upgrade your client to a newer version

### ISSUE THREAD

**Issue by hiwadolb** [LTD-Beget/sprutio#120]
Здравствуйте!

Выполняю установку по инструкции, при запуске **./run.sh** выходит ошибка **client version 1.18 is too old. Minimum supported API version is 1.24, please upgrade your client to a newer version**

Менял версии docker, результата нет. Пробовал поставить на Ubuntu 22.04, аналогичная ошибка. В чём может быть проблема? https://disk.yandex.ru/i/BWriXRl2zv3Hzg 

**Окружение:**
Ubuntu 20.04
Docker version 27.0.1, build 7fafd33
docker-compose version 1.29.2, build 5becea4c
Linux 5.4.0-182-generic #202-Ubuntu SMP Fri Apr 26 12:29:36 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

**Comment by hiwadolb** [comment]
Всё, проблема решена, сам ошибся, спасибо.

**Comment by ross6801** [comment]
please can you explain the solution? I have the same problem on debian 12. Thanks

**Comment by hiwadolb** [comment]
@ross6801 Hi, you can downgrade the docker version to 5:23 (or 5:22).
Below is the instruction for ubuntu (but it can be customized for Debian)

`for pkg in docker.io docker-doc docker-compose podman-docker containerd runc; do sudo apt-get remove $pkg; done`

`apt-get update`
`apt-get install ca-certificates curl gnupg`
`install -m 0755 -d /etc/apt/keyrings`
`curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg`
`chmod a+r /etc/apt/keyrings/docker.gpg`

```
echo \
  "deb [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
  "$(. /etc/os-release && echo "$VERSION_CODENAME")" stable" | \
  sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
```

Look version:
`apt-cache madison docker-ce | awk '{ print $3 }'`

We specify a certain version (using the example of the doker), sample:
`VERSION_STRING=5:23.0.2-1~ubuntu.22.04~jammy`
`apt-get install docker-ce=$VERSION_STRING docker-ce-cli=$VERSION_STRING containerd.io docker-buildx-plugin docker-compose-plugin`
`chmod +x /usr/bin/docker-compose`
`sync`
