### ISSUE TITLE
How do I change the default language to English?

### ISSUE THREAD

**Issue by Boss32** [LTD-Beget/sprutio#14]
How do I change the default language to English?

**Comment by Grey2k** [comment]
In file config 
https://github.com/LTD-Beget/sprutio/blob/master/app/config/settings.py

change that ones 
````python
DEFAULT_LANGUAGE = 'en'
DEFAULT_LOCALE = 'en_US'
````

**Comment by AlexeyManikin** [comment]
Add the language selection on the login page, soon.

**Comment by aait** [comment]
Thank you, Gray2K! In installed Sprut.io using manual (via Docker) https://github.com/LTD-Beget/sprutio.
Unfortunately, I am not familiar with Docker. Where i find same file to edit?

**Comment by Boss32** [comment]
Thank you, Gray2K! In installed Sprut.io using manual (via Docker) https://github.com/LTD-Beget/sprutio.
Unfortunately, I am not familiar with Docker. Where i find same file to edit?

**Comment by mlosev** [comment]
@Boss32 
you need to install  Sprut.io a bit differently in that case (until @Grey2k adds language selection to UI and to environment variables)

1) clone this repository
`git clone https://github.com/LTD-Beget/sprutio.git`

2) initialize submodules
`git submodule update --init --recursive`

3) change DEFAULT_LANGUAGE/DEFAULT_LOCALE in `app/config/settings.php`

4) run Sprut.io via `dev.sh` 
`./dev.sh up -d`

Remember to shutdown old Sprut.io instance (via `run.sh`) prior to use `dev.sh`

@Grey2k  will add language selection in near time (as I hope)

**Comment by tesargusmawan** [comment]
Any update on this?

**Comment by AlexeyManikin** [comment]
Done. 
https://github.com/LTD-Beget/sprutio/pull/32.

**Comment by tesargusmawan** [comment]
Where to select the language, login page? I already pulled the recent image from docker but there is no option for language.

**Comment by AlexeyManikin** [comment]
Update docker images now. Yes, you can change language on login pages and main pages on top right corner.

**Comment by AlexeyManikin** [comment]
<img style="width: 100px;" src="https://habrastorage.org/files/16b/765/fdf/16b765fdfede4dd582a46846965ad5de.png"/>

<img src="https://habrastorage.org/files/166/195/0bc/1661950bc14e4638a3284fe7546408cf.png"/>
