### ISSUE TITLE
Криво работает загрузка файлов

### ISSUE THREAD

**Issue by sd-design** [LTD-Beget/sprutio#16]
Загружаю файлы на сервак - закачивает (показывает, что 100: загружено), но в итоге файл имеет нулевой размер. Т. е. я в итоге получаю пустые файлы при загрузке.
Сервер на Ubuntu 15.10, Apache/2.4.12
Все встало хорошо - docker показывает все что нужно

**Comment by sd-design** [comment]
Разобрался - у меня на маке были права выставлены на чтение файла. Поэтому он и загружал пустышки. Даже на ваш демо-сервер

**Comment by sd-design** [comment]
Итог проблемы - попался какой-то "заколдованный" css-файл, который не хочет загружать ни на ваш демо-сервер не на мой сервер

**Comment by sd-design** [comment]
Можете пояснить - может это какой-нибудь кеш?

**Comment by sd-design** [comment]
Последнее наблюдение - менеджер не загружает файл меньше 1 КБ, независимо от расширения. Пробовал и .php и .css (если они меньше 1 КБ) загружаются пустышками.

**Comment by sd-design** [comment]
Нащупал минимальный размер файла, с которого менеджер начинает загружать на сервер - оказалось это 4 КБ

**Comment by Grey2k** [comment]
Возможно nginx не передает размер более 4KB в sprutio 
убедитесь что client_max_body_size - устновлена в приемлимое значение, например
````
client_max_body_size 100M;  
````

**Comment by sd-design** [comment]
Хотел узнать - проблему не решили? А то как-то перезаливать файлы меньше 4КБ превращается в проблему

**Comment by sd-design** [comment]
Ответьте - решился этот баг?

**Comment by sd-design** [comment]
Решился этот вопрос?

**Comment by f-andrey** [comment]
Да, натыкаешься на такое почти сразу, проблема похоже в том, что при копировании питон пытается интерпретировать файлы, типа html и прочие текстовые, почему такое происходит не докопался, вот сейчас похоже снова начну тестить, может откопаю.

**Comment by kirvesp** [comment]
Проблема в том, что возникает состояние гонки при получении данных из сокета между app-ом и rpc, который размещает уже полученный файл в нужном месте. Т.е. после получения последней порции данных app уже получил информацию о том, что соединение пора закрывать, а rpc ещё не закончил работу с файлом, т.к. только получил инфу из сокета. В итоге, происходит перемещение временного файла, который только создан, но ещё не записан, а уже после в него записываются данные из сокета. Баг решён, после новогодних праздников будут выложены фиксы для него.

**Comment by sd-design** [comment]
Супер!!!! Спасибо!
