### ISSUE TITLE
SFTP user can go up until the root parent directory

### ISSUE THREAD

**Issue by blackshrub** [LTD-Beget/sprutio#34]
**I create SFTP users with the steps below:**
1. Create new group called `ftpaccess` for SFTP users.
2. Comment out `Subsystem sftp /usr/lib/openssh/sftp-server` in `/etc/ssh/sshd_config`.
3. Add these lines to the end of the file `/etc/ssh/sshd_config`:
`Subsystem sftp internal-sftp`
`Match group ftpaccess`
`ChrootDirectory %h`
`X11Forwarding no`
`AllowTcpForwarding no`
`ForceCommand internal-sftp`
4. Create user with group and shell:
`sudo useradd -m john -g ftpaccess -s /usr/sbin/nologin`
5. Change ownership for the home dir:
`sudo chown root /home/john`
6. Create a folder inside home directory and assign ownership to john:
`sudo mkdir /home/john/www`
`sudo chown john:ftpaccess /home/john/www`

**Steps to reproduce:**
1. Login to sprut.io with the sftp user account
2. Click "Up" 

**Expected result:**
The sftp users can only access (read, write, execute) their own specific root directory and its subdirectories (/home/john/..).

**Actual result:**
The sftp users can access (read only) all file system by clicking Up button. They can open each folder and file, though they could not save the file if they try to edit it.

Did I miss any steps?
I tested the same sftp users via FTP Client and it worked well.

**Comment by kirvesp** [comment]
Hello,

Is this user on the same machine with sprutio instance?

**Comment by iamra** [comment]
I have the same experience with users being created by a hosting panel with chroot enabled. Not sure how sprutio handles this but I second this issue.

**Comment by blackshrub** [comment]
@kirvesp yes sure.

**Comment by kirvesp** [comment]
@blackshrub Sprutio uses pam auth for local users. So you need to set right permissions on dirs(disable r option for non-root users). Also i didn't find in sshd docs `ChrootDirectory` option. As i know it only works with ftp or sftp protocols in ftp-\sftp-server configs.

**Comment by kirvesp** [comment]
This is not a sprutio bug.
