### ISSUE TITLE
Интеграция

### ISSUE THREAD

**Issue by wormen** [LTD-Beget/sprutio#37]
Не нашел нигде никакой информации
1) как интегрировать в ОС
2) как синхронизировать авторизацию пользователей с другими системами, например как это сделано у вас на хостинге

заодно сюда же, несколько моментов, которые не имею отношение к интеграции ...
так же нету информации, как можно модифицировать панель, например лично меня интересует
1) как изменить внешний вид страницы авторизации. либо отключить эту форму
2) как модицировать интерфейс, например, добавление пунктов меню, как на скрине
![21-08-2016 21-47-12](https://cloud.githubusercontent.com/assets/8462339/17837259/f5e014b4-67e8-11e6-93f7-cfcc49758ae9.jpg)

других пользователей, думаю эти моменты не меньше меня интересуют
в идеале, не плохо бы было увидеть документацию к панели, а не только мануал по установке

**Comment by AlexeyManikin** [comment]
Добрый день. 

Первый вопрос не совсем ясен, что именно имеется в виду под интеграцией ? Это установка ? 
По поводу других сервисов - можно дописать плагин для авторизации через другие сервисы.

Далее по доработкам - весь код есть в проекте, страница авторизации https://github.com/LTD-Beget/sprutio/blob/master/app/public/login.html. Можно без нее, передавать токен (как сделано у нас на хостинге) или логин/пароль.

Интерфейс написан на ExtJS - можно посмотреть последние коммиты, там добавлялся webdav, примеры кода там есть.

**Comment by Grey2k** [comment]
Функция "Мой Компьютер" не реализована с sprut.io по двум причинам

- Это отдельный Java апплет, поддержка которых уже прекращена почти во всех современных браузерах.
- Для его работы требуется специальный сертификат, который выпускается на конкретную сборку и доменное имя, а также стоит денег, поэтому вы не сможете запустить его у себя.

По поводу интеграции - на linux системах файловый менеджер использует встроенную авторизацию, через модуль PAM - поэтому требуется только создать в системе пользователя - и он сможет зайти в файловый менеджер. 

Контроллер для авторизации 
https://github.com/LTD-Beget/sprutio/blob/master/app/handlers/AuthHandler.py

Модуль, где выполняется запрос на авторизацию
https://github.com/LTD-Beget/sprutio/blob/master/app/classes/core/FMAuth.py

Код авторизации на конечном сервере
https://github.com/LTD-Beget/sprutio-rpc/blob/023b20ecefd35154eb869487edb60f76ba8aa2d6/lib/FileManager/workers/baseWorkerCustomer.py#L32

Для интерфейса используется библиотека ExtJS 5.1.1

Ссылка на документацию
http://docs.sencha.com/extjs/5.1.1/index.html

Код приложения находится тут
https://github.com/LTD-Beget/sprutio-frontend/tree/master/app

Отвечая на ваш вопрос по поводу кнопочек и меню - вьюхи описаны тут
https://github.com/LTD-Beget/sprutio-frontend/tree/master/app/view/toolbars/coffee

Надеюсь что ответил на все ваши вопросы.

**Comment by wormen** [comment]
@Grey2k да, получил ответы на свои вопросы
появился еще 1 вопрос ....
правильно ли я понимаю, что если я собираюсь вносить какие-то изменения, то мне на основе вашего контейнера придется свой контейнер?
или есть какие-то варианты, чтобы можно было получать ваши обновления и при этом внести свои изменения?

**Comment by Grey2k** [comment]
Вы можете собрать свой контенер или не собирать его 
(настроив свое окружение самостоятельно)

Обновления придется мержить в git репозитории, если вы сделаете форк - как и с любым другим проектом. 

Так же если вы хотите добавить функциональность - мы всегда рады pull реквестам )

**Comment by wormen** [comment]
@Grey2k понял, спасибо

**Comment by wlatt1991** [comment]
> Добрый день.
> 
> Первый вопрос не совсем ясен, что именно имеется в виду под интеграцией ? Это установка ?
> По поводу других сервисов - можно дописать плагин для авторизации через другие сервисы.
> 
> Далее по доработкам - весь код есть в проекте, страница авторизации https://github.com/LTD-Beget/sprutio/blob/master/app/public/login.html. Можно без нее, передавать токен (как сделано у нас на хостинге) или логин/пароль.
> 
> Интерфейс написан на ExtJS - можно посмотреть последние коммиты, там добавлялся webdav, примеры кода там есть.

По поводу токена можно подробнее? Куда слать? Что за токен? Откуда его взять?
