### ISSUE TITLE
Не открывает удаленные сервера

### ISSUE THREAD

**Issue by AnatoliyAV** [LTD-Beget/sprutio#42]
Пробовал открывать разные ftp и sftp, с ip и через домен, у себя в менеджере и у вас в демо. 

Пишет не удалось открыть соединение. 

Скриншот http://prnt.sc/cl2xh0

**Comment by GRbit** [comment]
Только что проверил соединение через ftp и через ssh – работает как надо.
Не могли бы вы подробнее описать последовательность действий от начала до конца, чтобы было понятно как воспроизвести проблему?

**Comment by AnatoliyAV** [comment]
у меня есть хостинг здесь http://fastvps.ru/ и здесь https://getflywheel.com/ 

У первого FTP. Вставляю в менеджер хост (ip) логин и пароль, сохраняю, кликаю два раза для подключения, и выкидывает сразу сообщение (смотрите выше в скриншоте)

У второго SFTP (sftp.flywheelsites.com) делаю тоже самое все, порт 22, при подключении пишет сразу сообщение.

**Comment by AnatoliyAV** [comment]
Еще заметил, что бывает не срабатывает кнопка "Новое соединение", нажимаю и не чего не происходит.

Еще все верхние настройки FTP не сохраняються в списке. Когда открываю заного менеджер список пуст.

**Comment by AnatoliyAV** [comment]
Создал вам тестовый FTP 
5.45.116.35
login: test
pass: sprutio

Проверил, через FileZilla открывается.

**Comment by AnatoliyAV** [comment]
Нашел решение, придобавлении нового соединения делаю так:
Заполнил все поля нового FTP, нажал "Сохранить", закрыл окошко с списком FTP (**это важно**), потом заного открываю список и кликаю по нужному FTP = только тогда открывает FTP
