### ISSUE TITLE
Не идет аплоад файлов

### ISSUE THREAD

**Issue by Electronn** [LTD-Beget/sprutio#43]
Здравствуйте,

установка прошла чисто, контейнеры запущены, все функции кроме одной работают. Не идет аплоад файлов :
`BaseHandler.py[LINE:67]# ERROR    [2016-10-03 06:14:16,882] -- app -- login:root -- Traceback:Traceback (most recent call last):
  File "/app/handlers/BaseHandler.py", line 204, in catch
    return method(*args, **kwargs)
  File "/usr/local/lib/python3.4/site-packages/tornado/web.py", line 2743, in wrapper
    return method(self, *args, **kwargs)
  File "/app/handlers/UploadHandler.py", line 53, in post
    sock.connect((SENDFILE_DEFAULT_HOST, SENDFILE_DEFAULT_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
`

**Comment by f-andrey** [comment]
```
ConnectionRefusedError: [Errno 111] Connection refused
```
Это как то странно, что то может всё же не корректно поднялось.
Хотя и не должно, но если в контейнерах вдруг поднят дуалстек IPv4/IPv6, то такое бы могло быть, там надо по IPv4 обращаться, но вообще побольши бы логов и диагностики.

Я когда тестил месяца три назад, натыкался что там бывают проблемы с питоновскими зависимостями, но так же надо включать расширенный дебаг.

**Comment by kirvesp** [comment]
@Electronn Обновите образы спрутио и проверьте ещё раз, пожалуйста. Вероятно, у Вас не поднялся сервер загрузки файлов внутри контейнера rpc.

**Comment by kirvesp** [comment]
Давно нет отклика, проблема не воспроизводится.
