### ISSUE TITLE
Пользователь может подниматься выше своей домашней папки, читать и просматривать системные файлы

### ISSUE THREAD

**Issue by redcap52** [LTD-Beget/sprutio#44]
Здравствуйте!
Почему-то пользователь может подниматься выше своей домашней папки и просматривать системные файлы. Как устранить эту проблему?

**Comment by wlatt1991** [comment]
Ну так и как решился вопрос???

**Comment by dapapko** [comment]
> Ну так и как решился вопрос???

@wlatt1991 


Пришлось кое-что переписать, а именно добавить проверку на то, является ли пользователь с заданным логином владельцем директории, в которую хочет попасть клиент.
