### ISSUE TITLE
Не работает загрузка файлов.

### ISSUE THREAD

**Issue by skofields** [LTD-Beget/sprutio#49]
Установил все по инструкции, все работает как показалось на первый взгляд, единственное не загружаются файлы. Остальные функции вроде работают (удаление, перемещение, редактирование и др.) Еще заметил разархивация файлов работает только с zip файлами, rar отказывается открывать.  https://pp.vk.me/c837424/v837424132/15d4e/lGYpYgqjs2c.jpg 
https://pp.vk.me/c837424/v837424132/15d60/P6mOGcWoTO8.jpg
https://pp.vk.me/c837424/v837424132/15d57/i9TndDAwa4U.jpg

**Comment by kirvesp** [comment]
Поддержки rar-а пока нет, по проблеме с загрузкой: нужны данные из логов, чтобы понять, в чём конкретно ошибка. Нужны логи rpc и app.

**Comment by skofields** [comment]
как их получить?

**Comment by kirvesp** [comment]
После установки спрутио в директории с run.sh появляется директория logs, в которой будут находиться логи. Воспроизведите ошибку с загрузкой и приложите данные логов об этих действиях.

**Comment by skofields** [comment]
FM_APP_DEFAULT_RPC_HOST=fm-rpc
FM_APP_DEFAULT_RPC_PORT=8400
FM_APP_DEFAULT_PORT=8300
FM_APP_DEFAULT_HOST=0.0.0.0
FM_REDIS_HOST=fm-redis
FM_REDIS_PORT=6379
FM_REDIS_EXPIRE=86400
FM_APP_LOGDIR=/var/log/fm
FM_APP_SENDFILE_HOST=fm-rpc
FM_APP_SENDFILE_PORT=51600

FM_RPC_PROGRAM_NAME=fm-rpc
FM_RPC_HOST=0.0.0.0
FM_RPC_PORT=8400
FM_REDIS_HOST=fm-redis
FM_REDIS_PORT=6379
FM_REDIS_EXPIRE=86400
FM_RPC_SETTINGS_DB_PATH=/var/spool/fm/rpc.db
FM_RPC_LOGFILE=/var/log/fm/rpc.log
FM_RPC_ROOT_MOUNT_POINT=/mnt
FM_RPC_SENDFILE_HOST=0.0.0.0
FM_RPC_SENDFILE_PORT=51600
FM_RPC_SENDFILE_LOGFILE=/var/log/fm/sendfile.log

**Comment by kirvesp** [comment]
Я знаю содержимое конфигов, при установке по шагам из readme в директории, из которой производилась установка появятся логи.
` dev@cs44456:~$ ls -la | grep run`
`-rwxr-xr-x  1 root root     549 дек 23 10:55 run.sh`
`dev@cs44456:~$ ls -la | grep logs`
`drwxr-xr-x  2 root root    4096 дек 23 11:04 logs`
`dev@cs44456:~$ ls -la logs/`
`total 76`
`drwxr-xr-x  2 root root  4096 дек 23 11:04 .`
`drwxr-xr-x 13 dev  dev   4096 дек 23 11:02 ..`
`-rw-r--r--  1 root root  5560 дек 23 11:34 access.log`
`-rw-r--r--  1 root root  1362 дек 23 11:04 app.log`
`-rw-r--r--  1 root root   234 дек 23 10:57 error.log`
`-rw-r--r--  1 root root 20265 дек 23 11:34 rpc.log`
`-rw-r--r--  1 root root     0 дек 23 10:57 sendfile.log`
`-rw-r--r--  1 root root 30588 дек 23 11:34 static.log`
`-rw-r--r--  1 root root     0 дек 23 11:04 views.log`

**Comment by skofields** [comment]
# ls -la | grep run
-rwxr-xr-x   1 root   root       549 Dec 11 12:50 run.sh
# ls -la | grep logs
drwxr-xr-x   2 root   root      4096 Dec 11 12:52 logs
# ls -la logs/
total 16
drwxr-xr-x  2 root root 4096 Dec 11 12:52 .
dr-xr-x---. 9 root root 4096 Dec 11 12:51 ..
-rw-r--r--  1 root root  681 Dec 11 12:52 app.log
-rw-r--r--  1 root root  112 Dec 11 12:52 rpc.log
-rw-r--r--  1 root root    0 Dec 11 12:51 sendfile.log

**Comment by kirvesp** [comment]
Так, окей. Вы нашли логи. Отлично. Теперь сделайте tail -f путь_к_нужному_логу, воспроизведите в менеджере ошибку загрузки и скиньте вывод логов.

**Comment by skofields** [comment]
tail -f /opt/sprutio/logs/app.log
BaseHandler.py[LINE:55]# ERROR    [2016-12-23 09:04:36,967] -- app -- Handled exception in app.py: [Errno 111] Connection refusedTraceback:Traceback (most recent call last):
  File "/app/handlers/BaseHandler.py", line 204, in catch
    return method(*args, **kwargs)
  File "/usr/local/lib/python3.4/site-packages/tornado/web.py", line 2743, in wrapper
    return method(self, *args, **kwargs)
  File "/app/handlers/UploadHandler.py", line 53, in post
    sock.connect((SENDFILE_DEFAULT_HOST, SENDFILE_DEFAULT_PORT))
ConnectionRefusedError: [Errno 111] Connection refused

BaseHandler.py[LINE:67]# ERROR    [2016-12-23 09:04:36,969] -- app -- login:admin -- Traceback:Traceback (most recent call last):
  File "/app/handlers/BaseHandler.py", line 204, in catch
    return method(*args, **kwargs)
  File "/usr/local/lib/python3.4/site-packages/tornado/web.py", line 2743, in wrapper
    return method(self, *args, **kwargs)
  File "/app/handlers/UploadHandler.py", line 53, in post
    sock.connect((SENDFILE_DEFAULT_HOST, SENDFILE_DEFAULT_PORT))
ConnectionRefusedError: [Errno 111] Connection refused

tail -f /opt/sprutio/logs/rpc.log
BaseHandler.py[LINE:55]# ERROR    [2016-12-23 09:05:12,754] -- app -- Handled exception in app.py: [Errno 111] Connection refusedTraceback:Traceback (most recent call last):
  File "/app/handlers/BaseHandler.py", line 204, in catch
    return method(*args, **kwargs)
  File "/usr/local/lib/python3.4/site-packages/tornado/web.py", line 2743, in wrapper
    return method(self, *args, **kwargs)
  File "/app/handlers/UploadHandler.py", line 53, in post
    sock.connect((SENDFILE_DEFAULT_HOST, SENDFILE_DEFAULT_PORT))
ConnectionRefusedError: [Errno 111] Connection refused

BaseHandler.py[LINE:67]# ERROR    [2016-12-23 09:05:12,755] -- app -- login:admin -- Traceback:Traceback (most recent call last):
  File "/app/handlers/BaseHandler.py", line 204, in catch
    return method(*args, **kwargs)
  File "/usr/local/lib/python3.4/site-packages/tornado/web.py", line 2743, in wrapper
    return method(self, *args, **kwargs)
  File "/app/handlers/UploadHandler.py", line 53, in post
    sock.connect((SENDFILE_DEFAULT_HOST, SENDFILE_DEFAULT_PORT))
ConnectionRefusedError: [Errno 111] Connection refused

**Comment by kirvesp** [comment]
немного не понял. У Вас содержимое app.log и rpc.log идентичное?

**Comment by skofields** [comment]
судя по всему, вводил по очереди, сначала tail -f /opt/sprutio/logs/app.logзатем выполнил загрузку файла после тоже самое с tail -f /opt/sprutio/logs/rpc.log

**Comment by kirvesp** [comment]
это странно, рекомендую попробовать стопнуть, удалить все контейнеры и образы, а также их данные(всё, что есть в /opt/sprutio, кроме run.sh), и заново накатить спрутио.

**Comment by skofields** [comment]
# ./run.sh
Recreating sprutio_cron_1...
Cannot destroy container 5c99d91f894f62a4ce33e2de4d0efb4dc44e97ede245a8f67cc9a0f6c5a1d589: Driver devicemapper failed to remove root filesystem 5c99d91f894f62a4ce33e2de4d0efb4dc44e97ede245a8f67cc9a0f6c5a1d589: Device is Busy
#  ./run.sh
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.main", line 32, in main
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.docopt_command", line 21, in sys_dispatch
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.command", line 34, in dispatch
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.docopt_command", line 24, in dispatch
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.command", line 66, in perform_command
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.main", line 471, in up
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.project", line 230, in up
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.service", line 398, in remove_duplicate_containers
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.service", line 405, in duplicate_containers
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.service", line 106, in containers
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.container", line 28, in from_ps
TypeError: coercing to Unicode: need string or buffer, NoneType found

**Comment by kirvesp** [comment]
а контейнеры и образы перед этим были удалены? 
docker ps -a
docker images

**Comment by skofields** [comment]
Удалил все, что было в папке opt/sprutio/ кроме файла run.sh

# docker ps -a
CONTAINER ID        IMAGE                    COMMAND                CREATED             STATUS                      PORTS                                           NAMES
8cb0cfc16d3b        beget/sprutio-cron       "/init"                30 minutes ago      Up 30 minutes                                                               sprutio_cron_1
507ff6dd61cf        hello-world              "/hello"               32 minutes ago      Exited (0) 32 minutes ago                                                   boring_heisenberg
9fef3aed0d4b        beget/sprutio-nginx      "nginx -g 'daemon of   3 days ago          Up 3 days                   127.0.0.1:9080->80/tcp, 0.0.0.0:9443->443/tcp   sprutio_nginx_1
cd2ec60b0a82        beget/sprutio-app        "/init"                3 days ago          Up 3 days                                                                   sprutio_app_1
1877ea239b79        beget/sprutio-rpc        "/init"                3 days ago          Up 3 days                                                                   sprutio_rpc_1
c382710c7806        redis:3.0                "docker-entrypoint.s   3 days ago          Up 3 days                   6379/tcp                                        sprutio_redis_1
d4783ae8bd8d        beget/sprutio-frontend   "/bin/sh -c /bin/tru   3 days ago          Exited (0) 3 days ago                                                       sprutio_frontend_1
5c99d91f894f        beget/sprutio-cron       "/init"                3 days ago          Dead
e6d3457c43c4        hello-world              "/hello"               3 days ago          Exited (0) 3 days ago                                                       silly_turing
9ea1ab2a3616        hello-world              "/hello"               11 days ago         Exited (0) 11 days ago                                                      hopeful_archimedes
88271551738c        hello-world              "/hello"               13 days ago         Exited (0) 13 days ago                                                      ecstatic_cori
# docker images
REPOSITORY               TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
redis                    3.0                 45ec9ea54263        8 days ago          175.5 MB
<none>                   <none>              be44e0b0cdb1        6 weeks ago         175.4 MB
centos                   latest              97cad5e16cb6        7 weeks ago         196.5 MB
beget/sprutio-frontend   latest              16993134b572        3 months ago        261.5 MB
beget/sprutio-nginx      latest              357b17179d79        3 months ago        182.7 MB
beget/sprutio-app        latest              7d1cafa4383e        3 months ago        712.7 MB
beget/sprutio-rpc        latest              9a203f460787        3 months ago        775.5 MB
beget/sprutio-cron       latest              722b304bcc85        3 months ago        700 MB
hello-world              latest              f0cb9bdcaa69        5 months ago        1.848 kB

**Comment by kirvesp** [comment]
нужно контейнеры и образы снести. рекомендую ознакомиться: docker --help. Там есть краткое описание доступных команд. 
Пошагово:
1. Получить список контейнеров(всех).
2. Удалить все, относящиеся к sprutio
3. Повторить шаги 1 и 2 для списка образов

**Comment by skofields** [comment]
Не помогло, все вернулось на круги своя

**Comment by kirvesp** [comment]
т.е. ошибка также есть и логи оба идентичны?

**Comment by skofields** [comment]
После полной переустановки, загрузка по прежнему не работает и логи идентичны

**Comment by kirvesp** [comment]
@skofields обновите, пожалуйста, образы спрутио и сообщите, если ошибка повторяется. Скорее всего, до этого у Вас по какой-то причине не стартовал сервер загрузки файлов в контейнере sprutio_rpc_1

**Comment by skofields** [comment]
@kirvesp обновление не помогло

**Comment by kirvesp** [comment]
@skofields хорошо, тогда ещё раз примеры данных из логов, пожалуйста. И зайдите в контейнер ```docker exec -it sprutio_rpc_1 /bin/bash``` и приложите вывод ``ps aux``` из него.

**Comment by skofields** [comment]
total 1600
drwxr-xr-x  2 root root    4096 Dec 30 15:35 .
dr-xr-x---. 9 root root    4096 Dec 11 12:51 ..
-rw-r--r--  1 root root  164582 Feb 10 09:19 access.log
-rw-r--r--  1 root root   45218 Feb 10 09:19 app.log
-rw-r--r--  1 root root    3385 Feb 10 09:19 error.log
-rw-r--r--  1 root root 1027940 Feb 10 09:19 rpc.log
-rw-r--r--  1 root root       0 Dec 11 12:51 sendfile.log
-rw-r--r--  1 root root  363208 Feb 10 09:19 static.log
-rw-r--r--  1 root root       0 Dec 30 15:35 views.log

USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         1  0.0  0.0    132    48 ?        Ss    2016   0:00 s6-svscan -t0 /var/run/s6/services
root        21  0.0  0.0    136    48 ?        S     2016   0:00 s6-supervise s6-fdholderd
root       139  0.0  0.0    136    52 ?        S     2016  46:21 s6-supervise sendfile
root       140  0.0  0.0    136    52 ?        S     2016   0:00 s6-supervise rpc
root       142  0.0  2.8 236648 28808 ?        Ss    2016  16:38 python start.rpc.py
root     21889  0.0  0.2  21888  2084 ?        Ss   13:11   0:00 /bin/bash
root     22111  0.0  0.1  19128  1280 ?        R+   13:13   0:00 ps aux

**Comment by kirvesp** [comment]
@skofields ну да, у вас sendfile не поднимается. Попробуйте внутри контейнера запустить ```python start.sendfile.py``` и приложите его вывод. Если запустится без ошибок, то просто рестартаните контейнер ```sprutio_rpc_1``` и затем опять проверьте вывод ```ps aux``` в нём.

**Comment by skofields** [comment]
@kirvesp не помогло 

FM back-end RPC server
--------------------------
HOSTNAME: 9d635cb8e01e
LOGFILE: /var/log/fm/sendfile.log
Starting server
Got an exception: name 'socket' is not defined
Traceback (most recent call last):
  File "start.sendfile.py", line 213, in <module>
    server = Server((RPC_SENDFILE_HOST, RPC_SENDFILE_PORT))
  File "start.sendfile.py", line 142, in __init__
    self.create_socket(socket.AF_INET, socket.SOCK_STREAM)
NameError: name 'socket' is not defined

**Comment by kirvesp** [comment]
@skofields у вас ядро системы ниже 3.9. Проблема в этом. Обновите ядро хотя бы до 3.9 и будет работать.

**Comment by kirvesp** [comment]
Проблема была в не соответствии версии ядра системы
