### ISSUE TITLE
работа без установки

### ISSUE THREAD

**Issue by wormen** [LTD-Beget/sprutio#50]
подскажите, как вашу поделку можно использовать без установки, т.е. меня интересует момент, как можно установить через docker-compose в составе других образов

**Comment by kirvesp** [comment]
@wormen Хороший вопрос. 

Sprutio представляет собой сборку из нескольких docker-контейнеров. Потому всё зависит от конкретной ситуации. Можно его собрать в один общий докер-контейнер(будет докер в докере) и потом использовать по своему усмотрению, можно использовать часть из его образов, поменяв конфигурацию. 

Если вам необходимы готовые образы, то их можно получить с докер-хаба.
```
beget/sprutio-cron
beget/sprutio-rpc
beget/sprutio-app
beget/sprutio-nginx
beget/sprutio-frontend
```
