### ISSUE TITLE
Можете помочь с настройкой почтового сервера?

### ISSUE THREAD

**Issue by redcap52** [LTD-Beget/sprutio#55]
Подскажите, как настроить почтовый сервер (MySQL Backend +Postfix+Dovecot) так, чтобы я мог создавать почтовые ящики, удалять их и изменять пароли простым изменением записей в БД? Связку настроил, но почему-то она не работает. Готов предоставить все необходимые данные для доступа.
Подскажите, сколько будет стоить подобная услуга? (сервер - VPS вне технической площадки Beget)
Просто техническая поддержка моего провайдера наотрез отказалась решать эту проблему даже на платной основе.
Пытаюсь настроить сервер по этой статье: http://www.volmed.org.ru/wiki/index.php/%D0%9F%D0%BE%D1%87%D1%82%D0%BE%D0%B2%D1%8B%D0%B9_%D1%81%D0%B5%D1%80%D0%B2%D0%B5%D1%80_%D0%BD%D0%B0_%D0%B1%D0%B0%D0%B7%D0%B5_Postfix,_Dovecot_%D0%B8_Ubuntu_14.04_LTS
У себя в почтовом клиенте пытаюсь войти - ничего не выходит
http://188.120.251.147/afterlogic/
Логин:user1@volmed.org.ru
Пароль:user1_password
Возникает ошибка
Произошла ошибка при попытке соединения с почтовым сервером.

**Comment by kirvesp** [comment]
@redcap52 Здравствуйте, Sprut.io не является почтовым сервером. Если Вы являетесь нашим клиентом, то можете в панели управления обратиться через форму: https://cp.beget.com/support. Либо написать сюда: https://beget.com/ru/feedback.

Но, по-хорошему, это тема профильного ресурса. Рекомендую посмотреть в документацию по используемым инструментам и/или обратиться на toster, stackoverflow. Сейчас же могу сказать, что ваш клиент возвращает ошибку с кодом 901, в его документации должно быть её описание.
