### ISSUE TITLE
Не грузится из под root

### ISSUE THREAD

**Issue by sd-design** [LTD-Beget/sprutio#60]
В консоли браузера висит ошибка 500 при вызове actions/main/init_session
"Failed to load resource: the server responded with a status of 500 (Internal Server Error)"

**Comment by kirvesp** [comment]
@sd-design подробности в студию. Как устанавливали, что в логах спрутио, какие контейнеры запущены? Это всё-таки открытый и свободный проект, а не платная услуга с тех поддержкой)

Директория с логами будет находиться в том же месте, что и ```run.sh```. Для корректного сбора рекомендую в директории с установочным скриптом выполнить команду: ```chmod -R 777 logs```

**Comment by sd-design** [comment]
В app.log появляются такие записи: BaseHandler.py[LINE:57]# ERROR    [2017-02-09 22:06:53,500] -- app -- Handled exception in app.py: 'type'Traceback:Traceback (most recent call last):
  File "/app/handlers/BaseHandler.py", line 206, in catch
    return method(*args, **kwargs)
  File "/usr/local/lib/python3.4/site-packages/tornado/web.py", line 2743, in wrapper
    return method(self, *args, **kwargs)
  File "/app/handlers/actions/main/InitSessionHandler.py", line 18, in post
    action = self.get_action(name=FM.Actions.INIT_SESSION, module=session['type'],
KeyError: 'type'

BaseHandler.py[LINE:69]# ERROR    [2017-02-09 22:06:53,501] -- app -- login:root -- Traceback:Traceback (most recent call last):
  File "/app/handlers/BaseHandler.py", line 206, in catch
    return method(*args, **kwargs)
  File "/usr/local/lib/python3.4/site-packages/tornado/web.py", line 2743, in wrapper
    return method(self, *args, **kwargs)
  File "/app/handlers/actions/main/InitSessionHandler.py", line 18, in post
    action = self.get_action(name=FM.Actions.INIT_SESSION, module=session['type'],
KeyError: 'type'

BaseHandler.py[LINE:57]# ERROR    [2017-02-09 22:06:53,505] -- app -- Handled exception in app.py: 'type'Traceback:Traceback (most recent call last):
  File "/app/handlers/BaseHandler.py", line 206, in catch
    return method(*args, **kwargs)
  File "/usr/local/lib/python3.4/site-packages/tornado/web.py", line 2743, in wrapper
    return method(self, *args, **kwargs)
  File "/app/handlers/actions/main/InitSessionHandler.py", line 18, in post
    action = self.get_action(name=FM.Actions.INIT_SESSION, module=session['type'],
KeyError: 'type'

BaseHandler.py[LINE:69]# ERROR    [2017-02-09 22:06:53,506] -- app -- login:root -- Traceback:Traceback (most recent call last):
  File "/app/handlers/BaseHandler.py", line 206, in catch
    return method(*args, **kwargs)
  File "/usr/local/lib/python3.4/site-packages/tornado/web.py", line 2743, in wrapper
    return method(self, *args, **kwargs)
  File "/app/handlers/actions/main/InitSessionHandler.py", line 18, in post
    action = self.get_action(name=FM.Actions.INIT_SESSION, module=session['type'],
KeyError: 'type'

**Comment by sd-design** [comment]
Все проблему решил - сделал апгрейд Ubuntu с 15.01 до 16.04 и переустановил контейнеры docker
Все работает!

**Comment by kirvesp** [comment]
@sd-design выглядит так, будто фронт некорректные данные при логине передал. Если ещё будет повторяться, скиньте доступы, по которым можно будет воспроизвести этот баг.

**Comment by sd-design** [comment]
Это было на виртуальной машине Azure под Ubuntu 15.10. Переодически соскакивала авторизация если вкладка браузера была открытой долго и в бездействии.

**Comment by kirvesp** [comment]
@sd-design хм, возможно ещё редис внутри отваливался. Issue я закрываю, если проблема опять возникнет: сообщите здесь же. Переоткрою и попробуем разобраться.

**Comment by sd-design** [comment]
OK
