### ISSUE TITLE
Sprutio_frontend_1 socker crashes

### ISSUE THREAD

**Issue by thatvalis** [LTD-Beget/sprutio#61]
Hi, first of all I wanna say your software looks amazing and seems to work great.
However, the docker container sprutio_frontend_1 crashes directly after startup. Is that intended behavior? The rest of the Docker containers seem to work fine. I can still access the app and things seem to work, but maybe some functionality is broken due to the frontend container crashing.
Is this something I should fix, and if so, how?

**Comment by kirvesp** [comment]
Hi, @thatvalis. It is intended behavior. Don't worry:)

**Comment by thatvalis** [comment]
Ok thanks, maybe add a line about that in the readme, so future users aren't worried the installation malfunctioned. :-)
Thanks again for great software!
