### ISSUE TITLE
Защита от брутфорса

### ISSUE THREAD

**Issue by dstorozhuk** [LTD-Beget/sprutio#64]
Как реализована защита от брутфорса? 
Я попробовал несколько раз вводить неправильно пароль - система меня не блокирует на время.
Есть ли какая то защита от ботов?

**Comment by kirvesp** [comment]
@dstorozhuk на данный момент такой защиты не предусмотрено. Но, т.к. используется стандартная pam-аутентификация, то это скорее вопрос настройки сервера. К примеру, можно использовать fail2ban.
