### ISSUE TITLE
How to use own SSL cert

### ISSUE THREAD

**Issue by saitoh183** [LTD-Beget/sprutio#65]
i have pem files generated from Let's encrypt. I linked them to the /root/ssl folder and did a ./run.sh stop and the ./run.sh but im still getting the cert from sprutio.

**Comment by kirvesp** [comment]
Hi @saitoh183! You should place your certs in ssl dir inside sprutio root dir and then rebuild your images.

**Comment by saitoh183** [comment]
![image](https://cloud.githubusercontent.com/assets/1534197/26584191/fdf20594-4515-11e7-9694-ec7cd5689ffe.png)

I reran run.sh but it still shows the default cert. do i need to rename them to sprutio?

**Comment by kirvesp** [comment]
@saitoh183 yes, you should rename it

**Comment by saitoh183** [comment]
ok, thanks

Im guessing i cant use a reverse proxy since this runs a nginx inside the container?

**Comment by kirvesp** [comment]
@saitoh183 
Well, you can do it with little changes in docker-compose.yml. This depends only on container network settings. [docs](https://docs.docker.com/engine/userguide/networking/)

**Comment by saitoh183** [comment]
@kirvesp 

Well i tried it but it seemed like the php didn't follow. I have nginx on openmediavault and i tried to reverse proxy and it didn't work. 

_Sent from my Samsung SM-G950W using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by kirvesp** [comment]
@saitoh183 

Sorry, i doesn't understand what you really want to do. Could you clarify your expectations? Do you try to make a reverse proxy from your nginx to app container itself or to app nginx container?

**Comment by saitoh183** [comment]
@kirvesp 

The nginx is installed via openmediavault plugin. So it is running directly on host. But it is ok, I figured it out :) 

_Sent from my Samsung SM-G950W using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by kirvesp** [comment]
@saitoh183 

I'm glad that you solve your issue. 
Please, describe your solution here, so it will be useful for another users :)

**Comment by saitoh183** [comment]
@kirvesp 

what i did was simply add this to nginx to get reverse proxy working:

location / {
		
		proxy_pass https://localhost:9443; 
        	include /etc/nginx/proxy_params;
        	       
   		}

Then i was able to navigate to it using https://file.mydomain.com

Now i just need to figure out when i cant navigate outside the home folder of root user when i add a remote server

**Comment by kirvesp** [comment]
@saitoh183 
Oh, i see. So that's was just a problem with using proxy on nginx.

So, if you haven't more questions i'll close the issue

**Comment by Skippidar** [comment]
@saitoh183 

could you please explain how u configured nginx? It shows me only 404 error.

**Comment by isaipanelinha** [comment]
I would also like to know how it is possible to use SSL.
This project is fantastic, but the documentation on SSL does not help.
