### ISSUE TITLE
Не удалось восстановить состояние сеанса

### ISSUE THREAD

**Issue by bezumkin** [LTD-Beget/sprutio#66]
На сервере Ubuntu 14.04 LTS настроен jail с помощью [jailkit](https://olivier.sessink.nl/jailkit/) и все пользователи, кроме административных, живут там.

У них есть свой /etc/passwd и всё необходимое для нормальной работы через SSH и SFTP. Однако, при авторизации через sprut.io получаю вот такую картину
![2017-07-26 14 10 33](https://user-images.githubusercontent.com/1257284/28618283-8e44927e-720c-11e7-8052-f00ded7033bd.png)
Ни одного файла увидеть нельзя.

Если зайти административным пользователем - всё ок, проблем нет. Полагаю, sprut неправильно определяет, что пользователи находятся в chroot и пытается выйти выше него. 

Можно что-то с этим поделать? Если нужны какие-то конфиги или подробности - только скажите.

**Comment by kirvesp** [comment]
Здравствуйте, @bezumkin 

Было бы интересно посмотреть логи по sshd и ftp-серверу с Вашей стороны, чтобы локализовать проблему как-то.

**Comment by bezumkin** [comment]
sshd пишет логи в /var/log/auth.log, там нет никакой активности при работе в sprut. Даже на уровне DEBUG.

FTP сервера у меня вообще нет, только SSH и SFTP.

**Comment by bezumkin** [comment]
Догадался посмотреть в консоль браузера, там ошибка 500 при входе, сервер выбрасывает
```
{"error": true, "message": "[Errno 2] No such file or directory: '/mnt/home/s1'", "traceback": "Traceback (most recent call last):\n  File \"/rpc/lib/FileManager/workers/main/initSession.py\", line 24, in run\n    \"listing\": self.make_listing(),\n  File \"/rpc/lib/FileManager/workers/main/initSession.py\", line 230, in make_listing\n    self.__list_recursive(abs_path, items, 1)\n  File \"/rpc/lib/FileManager/workers/main/initSession.py\", line 272, in __list_recursive\n    for item in os.listdir(path):\nFileNotFoundError: [Errno 2] No such file or directory: '/mnt/home/s1'\n"}
```

**Comment by bezumkin** [comment]
Так, проблема ясна:
- у меня в /etc/passwd домашняя директори указана как /home/s1
- /home/s1 существует, но является ссылкой на /jail/home/s1 - отсюда и ошибка, ссылка не обрабатывается правильно

Если же поменять домашнюю директорию на /jail/home/s1, то sprut начинает работать, но юзер видит, что он в jail и легко оттуда выходит выше. 
![2017-07-26 16 15 40](https://user-images.githubusercontent.com/1257284/28622576-b8de9078-721d-11e7-9c9d-400e6152be7c.png)

Изменить он, конечно, ничего не может, но всё равно неприятно. Похоже, sprut.io не уважает chroot.

**Comment by bezumkin** [comment]
В итоге пришёл к простому и очевидному решению (для тех, кто знаком с Docker). Нужно просто монтировать не весь сервер, а только мой chroot в директории jail:
```
rpc:
  image: beget/sprutio-rpc
  links:
    - redis:fm-redis
  volumes_from:
    - cron
  volumes:
    - "/jail:/mnt:rw"
```
И не забыть положить в `/jail/etc/shadow` записи о юзерах, чтобы они могли нормально авторизоваться.

И всё работает, спасибо!

**Comment by kirvesp** [comment]
Что ж, спасибо за интересное решение @bezumkin. Это любопытная история :)
Issue я закрываю, т.к. решение Вы сами предоставили
