### ISSUE TITLE
Issues with first login after installation!

### ISSUE THREAD

**Issue by Miimiikrii** [LTD-Beget/sprutio#78]
I install Sprutio after this guide https://sprut.io/en/install on an Ubuntu 16.04 LTS Server 64bit + Plesk Onyx.
I think the installation goes right, but i have some problems with my login. I dont know which data i have to type in for my first login as an admin. 

![2](https://user-images.githubusercontent.com/33722355/32892922-13847110-cad8-11e7-9bdc-007c28a7ecc1.PNG)

I dont know what i should type in here?! 

Server IP: https://81.169.218.130:9443/login?next=%2F

Or maby it is a bug?

**Comment by jerrdasur** [comment]
Hi, @Miimiikrii 

You should write here your server user credentials(such as for a SSH connection). In sprutio we use standard linux PAM.
